/**
 * v3-radio-group
 */
export const RADIO_GROUP_CHANGE_FUNC_PROVIDE = Symbol(
	'RADIO_GROUP_CHANGE_FUNC_PROVIDE'
);
export const RADIO_GROUP_INSTANCE_PROVIDE = Symbol(
	'RADIO_GROUP_INSTANCE_PROVIDE'
);
