/**
 * v3-radio-group
 */
export const RADIO_GROUP_CHANGE_FUNC_PROVIDE = Symbol(
	'RADIO_GROUP_CHANGE_FUNC_PROVIDE'
);
export const RADIO_GROUP_INSTANCE_PROVIDE = Symbol(
	'RADIO_GROUP_INSTANCE_PROVIDE'
);

/**
 * v3-checkbox-group
 */
export const CHECKBOX_GROUP_CHANGE_FUNC_PROVIDE = Symbol(
	'CHECKBOX_GROUP_CHANGE_FUNC_PROVIDE'
);
export const CHECKBOX_GROUP_INSTANCE_PROVIDE = Symbol(
	'CHECKBOX_GROUP_INSTANCE_PROVIDE'
);
export const CHECKBOX_GROUP_ADD_INSTANCE_FUNC_PROVIDE = Symbol(
	'CHECKBOX_GROUP_ADD_INSTANCE_FUNC_PROVIDE'
);

/**
 * v3-row
 */
export const ROW_INSTANCE_PROVIDE = Symbol('ROW_INSTANCE_PROVIDE');

/**
 * v3-select
 */
export const SELECT_INSTANCE_PROVIDE = Symbol('SELECT_INSTANCE_PROVIDE');
