export type ICheckboxBorder = boolean;
export type ICheckboxLabel = string | boolean | number;
export type ICheckboxMin = number;
export type ICheckboxMax = number;
export type ICheckboxIndeterminate = boolean;
export type ICheckboxSelectedIcon = string;
export type ICheckboxDefaultIcon = string;
export type ICheckboxIndeterminatedIcon = string;
export type ICheckboxDisabled = boolean;
